import { Course } from "./course-data";
import { aiM1Experiments } from "./ai-m1-data";
import { aiM2Experiments } from "./ai-m2-data";
import { aiM3Experiments } from "./ai-m3-data";
import { aiM4Experiments } from "./ai-m4-data";
import { aiM5Experiments } from "./ai-m5-data";
import { aiToolsShortNotes } from "./ai-tools-short-notes";

export const aiCourse: Course = {
  id: "ai-tools",
  title: "AI Tools Lab",
  objectives: [
    "To familiarize students with leading AI tools across key domains of creative and technical work.",
    "To develop critical evaluation skills by comparing tools on quality, speed, accuracy, and usability.",
    "To build confidence in using AI as a collaborative partner rather than a replacement.",
    "To encourage ethical reflection on the use, limitations, and impact of AI-generated content.",
    "To prepare students for AI-integrated professional environments."
  ],
  introduction: [
    "The AI Tools Lab is a hands-on exploration environment designed to give students direct, practical experience with the most powerful and widely-used artificial intelligence tools available today. Across five specialized lab stations — Image Generation, Writing, Coding, Web Design, and Research & Productivity — students engage with real tools in real workflows, moving beyond theory into applied understanding. Each lab mirrors the kinds of tasks professionals are already doing with AI in industry, making this experience immediately relevant and career-ready.",
    "[HTML]:<div class=\"mt-8 relative overflow-hidden rounded-2xl border border-blue-500/30 bg-gradient-to-br from-blue-900/40 via-slate-900/60 to-purple-900/40 p-8 shadow-2xl backdrop-blur-md\"><div class=\"absolute -top-24 -right-24 w-48 h-48 bg-blue-500/20 rounded-full blur-3xl\"></div><div class=\"absolute -bottom-24 -left-24 w-48 h-48 bg-purple-500/20 rounded-full blur-3xl\"></div><div class=\"relative z-10\"><div class=\"flex items-center gap-3 mb-6 border-b border-blue-500/30 pb-4\"><div class=\"p-2.5 rounded-xl bg-blue-500/20 border border-blue-500/40\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"text-blue-400\"><path d=\"M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z\"></path><polyline points=\"14 2 14 8 20 8\"></polyline><line x1=\"16\" y1=\"13\" x2=\"8\" y2=\"13\"></line><line x1=\"16\" y1=\"17\" x2=\"8\" y2=\"17\"></line><polyline points=\"10 9 9 9 8 9\"></polyline></svg></div><h3 class=\"text-2xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-400\">Structured Feedback Report Format</h3></div><p class=\"text-slate-300 mb-8 leading-relaxed text-lg\">After completing each experiment, students must submit a structured feedback report covering the following sections to ensure comprehensive evaluation of the AI tools used:</p><div class=\"grid grid-cols-1 md:grid-cols-2 gap-4\"><div class=\"flex gap-4 p-4 rounded-xl bg-slate-800/50 border border-slate-700/50 hover:bg-slate-800 hover:border-blue-500/50 transition-colors\"><div class=\"flex-shrink-0 w-8 h-8 rounded-full bg-blue-500/20 flex items-center justify-center text-blue-400 font-bold border border-blue-500/30\">1</div><div><h4 class=\"font-semibold text-white mb-1\">Tool Used</h4><p class=\"text-sm text-slate-400\">Name of the AI tool and the lab station it belongs to.</p></div></div><div class=\"flex gap-4 p-4 rounded-xl bg-slate-800/50 border border-slate-700/50 hover:bg-slate-800 hover:border-blue-500/50 transition-colors\"><div class=\"flex-shrink-0 w-8 h-8 rounded-full bg-blue-500/20 flex items-center justify-center text-blue-400 font-bold border border-blue-500/30\">2</div><div><h4 class=\"font-semibold text-white mb-1\">Task Performed</h4><p class=\"text-sm text-slate-400\">A brief description of the experiment carried out (2–3 sentences).</p></div></div><div class=\"flex gap-4 p-4 rounded-xl bg-slate-800/50 border border-slate-700/50 hover:bg-slate-800 hover:border-blue-500/50 transition-colors\"><div class=\"flex-shrink-0 w-8 h-8 rounded-full bg-blue-500/20 flex items-center justify-center text-blue-400 font-bold border border-blue-500/30\">3</div><div><h4 class=\"font-semibold text-white mb-1\">Prompt / Input Given</h4><p class=\"text-sm text-slate-400\">The exact prompt or input used, so results are reproducible and comparable.</p></div></div><div class=\"flex gap-4 p-4 rounded-xl bg-slate-800/50 border border-slate-700/50 hover:bg-slate-800 hover:border-blue-500/50 transition-colors\"><div class=\"flex-shrink-0 w-8 h-8 rounded-full bg-blue-500/20 flex items-center justify-center text-blue-400 font-bold border border-blue-500/30\">4</div><div><h4 class=\"font-semibold text-white mb-1\">Output Observed</h4><p class=\"text-sm text-slate-400\">A description or screenshot of the output generated by the tool.</p></div></div><div class=\"flex gap-4 p-4 rounded-xl bg-slate-800/50 border border-slate-700/50 hover:bg-slate-800 hover:border-purple-500/50 transition-colors md:col-span-2\"><div class=\"flex-shrink-0 w-8 h-8 rounded-full bg-purple-500/20 flex items-center justify-center text-purple-400 font-bold border border-purple-500/30\">5</div><div><h4 class=\"font-semibold text-white mb-1\">Quality Assessment</h4><p class=\"text-sm text-slate-400\">Rate the output on Accuracy, Relevance, Creativity/Originality, Ease of Use, and Speed (scale of 1–5).</p></div></div><div class=\"flex gap-4 p-4 rounded-xl bg-slate-800/50 border border-slate-700/50 hover:bg-slate-800 hover:border-purple-500/50 transition-colors\"><div class=\"flex-shrink-0 w-8 h-8 rounded-full bg-purple-500/20 flex items-center justify-center text-purple-400 font-bold border border-purple-500/30\">6</div><div><h4 class=\"font-semibold text-white mb-1\">Comparison</h4><p class=\"text-sm text-slate-400\">If the same task was performed on multiple tools, note key differences in output quality, tone, style, or usability.</p></div></div><div class=\"flex gap-4 p-4 rounded-xl bg-slate-800/50 border border-slate-700/50 hover:bg-slate-800 hover:border-purple-500/50 transition-colors\"><div class=\"flex-shrink-0 w-8 h-8 rounded-full bg-purple-500/20 flex items-center justify-center text-purple-400 font-bold border border-purple-500/30\">7</div><div><h4 class=\"font-semibold text-white mb-1\">Limitations Noticed</h4><p class=\"text-sm text-slate-400\">Any errors, hallucinations, biases, refusals, or gaps observed.</p></div></div><div class=\"flex gap-4 p-4 rounded-xl bg-slate-800/50 border border-slate-700/50 hover:bg-slate-800 hover:border-cyan-500/50 transition-colors md:col-span-2\"><div class=\"flex-shrink-0 w-8 h-8 rounded-full bg-cyan-500/20 flex items-center justify-center text-cyan-400 font-bold border border-cyan-500/30\">8</div><div><h4 class=\"font-semibold text-white mb-1\">Learning Outcome</h4><p class=\"text-sm text-slate-400\">What did you learn from this experiment? How does it change or inform how you would use this tool in a real-world scenario?</p></div></div><div class=\"flex gap-4 p-4 rounded-xl bg-slate-800/50 border border-slate-700/50 hover:bg-slate-800 hover:border-cyan-500/50 transition-colors\"><div class=\"flex-shrink-0 w-8 h-8 rounded-full bg-cyan-500/20 flex items-center justify-center text-cyan-400 font-bold border border-cyan-500/30\">9</div><div><h4 class=\"font-semibold text-white mb-1\">Ethical Observation</h4><p class=\"text-sm text-slate-400\">Any privacy, copyright, or bias concerns noted. (Optional but Recommended)</p></div></div><div class=\"flex gap-4 p-4 rounded-xl bg-gradient-to-r from-blue-900/50 to-purple-900/50 border border-blue-500/50 hover:border-blue-400 transition-colors shadow-[0_0_15px_rgba(59,130,246,0.2)]\"><div class=\"flex-shrink-0 w-8 h-8 rounded-full bg-gradient-to-br from-blue-400 to-purple-400 flex items-center justify-center text-white font-bold shadow-lg\">10</div><div><h4 class=\"font-semibold text-white mb-1 flex items-center gap-2\">Overall Rating <span class=\"px-2 py-0.5 rounded text-[10px] uppercase font-bold bg-blue-500/20 text-blue-300 border border-blue-500/30\">Scale 1–10</span></h4><p class=\"text-sm text-blue-200/80\">A final score and a one-sentence verdict on the tool’s usefulness.</p></div></div></div></div></div>"
  ],
  shortNotes: aiToolsShortNotes,
  targetAudience: {
    primary: "This lab is intended for undergraduate and postgraduate students across disciplines including Computer Science, Information Technology, Design, Mass Communication, Business, and any program where digital literacy and AI fluency are relevant.",
    prerequisites: [
      "No prior experience with AI tools is required.",
      "Basic digital literacy and web navigation skills."
    ],
    usefulFor: [
      "Students preparing for AI-integrated professional environments.",
      "Professionals seeking hands-on exposure to modern AI workflows.",
      "Educators designing practical AI curricula."
    ]
  },
  alignment: {
    university: "General Curriculum / Institutional Agnostic",
    department: "Cross-Disciplinary",
    course: "AI Tools Lab",
    credits: "L:0 T:0 P:3 C:1.5",
    yearSem: "All Semesters",
    branches: "Computer Science, IT, Design, Business, Mass Comm",
    totalExperiments: "20 experiments across 5 modules",
    compiler: "Various Web-based AI Tools (ChatGPT, Midjourney, Claude, Lovable, Cursor etc.)",
    units: [
      { unit: "Module 1", topics: "Image Generation Lab", weeks: "Weeks 1-2" },
      { unit: "Module 2", topics: "Writing Lab", weeks: "Weeks 3-4" },
      { unit: "Module 3", topics: "Coding Lab", weeks: "Weeks 5-6" },
      { unit: "Module 4", topics: "Web Design Lab", weeks: "Weeks 7-8" },
      { unit: "Module 5", topics: "Research & Productivity Lab", weeks: "Weeks 9-10" }
    ]
  },
  weeks: [
    {
      title: "🎨 Image Generation Lab",
      objective: "Explore visual AI generation using state-of-the-art text-to-image models.",
      tutorial: "Module 1: Visual AI Basics",
      labTitle: "Lab 1: Concept to Canvas",
      experiments: aiM1Experiments
    },
    {
      title: "✍️ Writing Lab",
      objective: "Enhance writing and analysis using Large Language Models.",
      tutorial: "Module 2: Generative Text",
      labTitle: "Lab 2: The AI Co-Writer",
      experiments: aiM2Experiments
    },
    {
      title: "💻 Coding Lab",
      objective: "Leverage AI assistants for code generation, debugging, and refactoring.",
      tutorial: "Module 3: AI in Software Development",
      labTitle: "Lab 3: The AI Pair Programmer",
      experiments: aiM3Experiments
    },
    {
      title: "✨ Web Design Lab",
      objective: "Generate and iterate on UI/UX designs using AI platforms.",
      tutorial: "Module 4: Generative UI",
      labTitle: "Lab 4: Zero to Website",
      experiments: aiM4Experiments
    },
    {
      title: "🧠 Research & Productivity Lab",
      objective: "Streamline knowledge work using AI-powered productivity tools.",
      tutorial: "Module 5: AI Workflows",
      labTitle: "Lab 5: The Augmented Knowledge Worker",
      experiments: aiM5Experiments
    }
  ]
};
