import { Course } from "./course-data";
import { aiM1Experiments } from "./ai-m1-data";
import { aiM2Experiments } from "./ai-m2-data";
import { aiM3Experiments } from "./ai-m3-data";
import { aiM4Experiments } from "./ai-m4-data";
import { aiM5Experiments } from "./ai-m5-data";
import { aiToolsShortNotes } from "./ai-tools-short-notes";

export const aiCourse: Course = {
  id: "ai-tools",
  title: "AI Tools Lab",
  objectives: [
    "To familiarize students with leading AI tools across key domains of creative and technical work.",
    "To develop critical evaluation skills by comparing tools on quality, speed, accuracy, and usability.",
    "To build confidence in using AI as a collaborative partner rather than a replacement.",
    "To encourage ethical reflection on the use, limitations, and impact of AI-generated content.",
    "To prepare students for AI-integrated professional environments."
  ],
  introduction: [
    "The AI Tools Lab is a hands-on exploration environment designed to give students direct, practical experience with the most powerful and widely-used artificial intelligence tools available today. Across five specialized lab stations — Image Generation, Writing, Coding, Web Design, and Research & Productivity — students engage with real tools in real workflows, moving beyond theory into applied understanding. Each lab mirrors the kinds of tasks professionals are already doing with AI in industry, making this experience immediately relevant and career-ready.",
    "**Feedback Structure:** After completing each experiment, students must submit a structured feedback report covering the following sections:",
    "1. **Tool Used:** Name of the AI tool and the lab station it belongs to.",
    "2. **Task Performed:** A brief description of the experiment carried out (2–3 sentences).",
    "3. **Prompt / Input Given:** The exact prompt or input used, so results are reproducible and comparable.",
    "4. **Output Observed:** A description or screenshot of the output generated by the tool.",
    "5. **Quality Assessment:** Rate the output on Accuracy, Relevance, Creativity/Originality, Ease of Use, and Speed (scale of 1–5).",
    "6. **Comparison:** If the same task was performed on multiple tools, note key differences in output quality, tone, style, or usability.",
    "7. **Limitations Noticed:** Any errors, hallucinations, biases, refusals, or gaps observed.",
    "8. **Learning Outcome:** What did you learn from this experiment? How does it change or inform how you would use this tool in a real-world context?",
    "9. **Ethical Observation:** Note any ethical considerations raised by the tool's output — including issues of originality, attribution, bias, or misuse potential.",
    "10. **Overall Rating:** A single overall rating (1–5 stars) with a one-line justification."
  ],
  shortNotes: aiToolsShortNotes,
  targetAudience: {
    primary: "This lab is intended for undergraduate and postgraduate students across disciplines including Computer Science, Information Technology, Design, Mass Communication, Business, and any program where digital literacy and AI fluency are relevant.",
    prerequisites: [
      "No prior experience with AI tools is required.",
      "Basic digital literacy and web navigation skills."
    ],
    usefulFor: [
      "Students preparing for AI-integrated professional environments.",
      "Professionals seeking hands-on exposure to modern AI workflows.",
      "Educators designing practical AI curricula."
    ]
  },
  alignment: {
    university: "General Curriculum / Institutional Agnostic",
    department: "Cross-Disciplinary",
    course: "AI Tools Lab",
    credits: "L:0 T:0 P:3 C:1.5",
    yearSem: "All Semesters",
    branches: "Computer Science, IT, Design, Business, Mass Comm",
    totalExperiments: "20 experiments across 5 modules",
    compiler: "Various Web-based AI Tools (ChatGPT, Midjourney, Claude, Lovable, Cursor etc.)",
    units: [
      { unit: "Module 1", topics: "Image Generation Lab", weeks: "Weeks 1-2" },
      { unit: "Module 2", topics: "Writing Lab", weeks: "Weeks 3-4" },
      { unit: "Module 3", topics: "Coding Lab", weeks: "Weeks 5-6" },
      { unit: "Module 4", topics: "Web Design Lab", weeks: "Weeks 7-8" },
      { unit: "Module 5", topics: "Research & Productivity Lab", weeks: "Weeks 9-10" }
    ]
  },
  weeks: [
    {
      title: "🎨 Image Generation Lab",
      objective: "Explore visual AI generation using state-of-the-art text-to-image models.",
      tutorial: "Module 1: Visual AI Basics",
      labTitle: "Lab 1: Concept to Canvas",
      experiments: aiM1Experiments
    },
    {
      title: "✍️ Writing Lab",
      objective: "Enhance writing and analysis using Large Language Models.",
      tutorial: "Module 2: Generative Text",
      labTitle: "Lab 2: The AI Co-Writer",
      experiments: aiM2Experiments
    },
    {
      title: "💻 Coding Lab",
      objective: "Leverage AI assistants for code generation, debugging, and refactoring.",
      tutorial: "Module 3: AI in Software Development",
      labTitle: "Lab 3: The AI Pair Programmer",
      experiments: aiM3Experiments
    },
    {
      title: "✨ Web Design Lab",
      objective: "Generate and iterate on UI/UX designs using AI platforms.",
      tutorial: "Module 4: Generative UI",
      labTitle: "Lab 4: Zero to Website",
      experiments: aiM4Experiments
    },
    {
      title: "🧠 Research & Productivity Lab",
      objective: "Streamline knowledge work using AI-powered productivity tools.",
      tutorial: "Module 5: AI Workflows",
      labTitle: "Lab 5: The Augmented Knowledge Worker",
      experiments: aiM5Experiments
    }
  ]
};
