const questions = [
// PRE-TEST QUESTIONS: Week 2 (Variables, Data Types, Format Specifiers, Standard I/O)
{ question: "Which of the following is a fundamental data type used to store whole numbers in C?", options: ["float", "char", "int", "double"], answerIndex: 2 },
{ question: "What is the primary purpose of a variable declaration in C?", options: ["To execute a calculation", "To allocate memory and specify the data type of an identifier", "To include system libraries", "To clear terminal outputs"], answerIndex: 1 },
{ question: "Which format specifier is typically used with printf() to display a single character?", options: ["%d", "%f", "%c", "%s"], answerIndex: 2 },
{ question: "How much memory does a standard 'char' data type occupy in most C implementations?", options: ["1 byte", "2 bytes", "4 bytes", "8 bytes"], answerIndex: 0 },
{ question: "Which of these is a valid variable name in C?", options: ["2totalAmount", "total_amount", "total$amount", "default"], answerIndex: 1 },
{ question: "Which standard I/O function is used to read formatted input from the keyboard?", options: ["printf()", "scanf()", "putchar()", "puts()"], answerIndex: 1 },
{ question: "What is the format specifier used to print a standard floating-point number (%f)?", options: ["%d", "%c", "%f", "%lf"], answerIndex: 2 },
{ question: "Which of the following data types can store numbers with fractional or decimal parts?", options: ["int", "char", "float", "short"], answerIndex: 2 },
{ question: "What symbol must precede the variable name inside a basic scanf() call to pass its memory address?", options: ["*", "#", "&", "$"], answerIndex: 2 },
{ question: "Which of the following statements about C identifiers is true?", options: ["They are case-insensitive", "They can start with a digit", "They cannot contain underscores", "They cannot match a reserved C keyword"], answerIndex: 3 },
{ question: "What escape sequence is used to insert a newline character into a printf string?", options: ["\t", "\n", "\b", "\r"], answerIndex: 1 },
{ question: "What happens if you define a variable but do not initialize it before reading its value?", options: ["It defaults to 0 automatically", "It causes a compile-time error", "It contains an unpredictable 'garbage' value", "The program safely halts"], answerIndex: 2 },
{ question: "Which keyword is used to define a variable whose value cannot be modified after initialization?", options: ["static", "const", "volatile", "extern"], answerIndex: 1 },
{ question: "What does the data type 'double' offer compared to 'float'?", options: ["It stores characters faster", "It provides higher precision and double the memory allocation size", "It is only used for negative integers", "It uses less memory"], answerIndex: 1 },
{ question: "Which header file must be included to use printf() and scanf()?", options: ["<stdlib.h>", "<math.h>", "<stdio.h>", "<string.h>"], answerIndex: 2 },
{ question: "Which character constant is represented correctly in C?", options: ["\"A\"", "'A'", "A", "\\A"], answerIndex: 1 },
{ question: "What is the size of an 'int' data type on a standard 32-bit/64-bit modern architecture?", options: ["1 byte", "2 bytes", "4 bytes", "8 bytes"], answerIndex: 2 },
{ question: "What does the escape sequence '\\t' represent?", options: ["A vertical backspace", "A horizontal tab", "A newline", "A null terminator"], answerIndex: 1 },
{ question: "Which data type is best suited to store the status of a switch (0 or 1) with minimum memory footprint in standard legacy C?", options: ["double", "float", "char", "long"], answerIndex: 2 },
{ question: "What function outputs a single character directly to the standard screen console?", options: ["scanf()", "getchar()", "putchar()", "puts()"], answerIndex: 2 },
{ question: "Which of these is an invalid constant character declaration?", options: ["'x'", "'\\n'", "'xyz'", "'7'"], answerIndex: 2 },
{ question: "What does the 'scanf' function return upon successful reading of items?", options: ["The value read from the console", "The number of input items successfully matched and assigned", "Always returns 0", "Always returns 1"], answerIndex: 1 },
{ question: "Which format specifier is used for a signed short integer?", options: ["%d", "%hd", "%ld", "%f"], answerIndex: 1 },
{ question: "What is the default fractional precision shown when using %f in a printf statement without specifications?", options: ["2 decimal places", "4 decimal places", "6 decimal places", "8 decimal places"], answerIndex: 2 },
{ question: "Can a C variable name contain spaces?", options: ["Yes, if enclosed in quotes", "No, spaces are strictly prohibited in identifiers", "Yes, anytime", "Only within function names"], answerIndex: 1 },

// POST-TEST QUESTIONS: Week 2 (Variables, Data Types, Format Specifiers, Standard I/O)
{ question: "What is the output of the following code?\nint x = 10;\nprintf(\"%d\", x);", options: ["x", "10", "%d", "Error"], answerIndex: 1 },
{ question: "What error or warning occurs in this statement: scanf(\"%d\", val); where val is an integer variable?", options: ["Missing quotes", "Missing address-of operator (&val)", "Incorrect format specifier", "No error present"], answerIndex: 1 },
{ question: "What is printed by the following statement?\nprintf(\"Hello\\nWorld\");", options: ["Hello, followed by a newline and World", "Hello\nWorld", "HelloWorld", "Hello followed by an error"], answerIndex: 1 },
{ question: "Given: float price = 5.257; What is the output of printf(\"%.2f\", price);?", options: ["5.2", "5.25", "5.26", "5.257"], answerIndex: 2 },
{ question: "What happens if you execute: char ch = 'A'; printf(\"%d\", ch);?", options: ["It prints the character 'A'", "It throws a compiler type-mismatch error", "It prints the ASCII decimal value of 'A' (65)", "It prints 0"], answerIndex: 2 },
{ question: "What is the output of the following code snippet?\nint a = 5, b = 10;\nprintf(\"%d %d\", b, a);", options: ["5 10", "10 5", "1015", "510"], answerIndex: 1 },
{ question: "If the input string provided in the console terminal is '25 45', what values are loaded by: scanf(\"%d %d\", &x, &y);?", options: ["x=25, y=45", "x=45, y=25", "x=25, y=0", "x=0, y=45"], answerIndex: 0 },
{ question: "What is the outcome of the following variable declaration: int gross-salary;", options: ["Declares a variable named gross-salary", "It causes a compilation syntax error because '-' is an operator", "It initializes a negative integer", "It compiles without error"], answerIndex: 1 },
{ question: "What is printed by: \nint n = 7;\nprintf(\"%03d\", n);", options: ["7", "700", "007", "037"], answerIndex: 2 },
{ question: "What is the structural problem with this statement: const int MAX = 100; MAX = 200;", options: ["It compiles fine and updates MAX", "It results in a compile-time error because a const variable cannot be reassigned", "It outputs a runtime error", "It sets MAX to zero"], answerIndex: 1 },
{ question: "What format specifier should be used to scan values into a 'double' variable using scanf()?", options: ["%f", "%lf", "%d", "%g"], answerIndex: 1 },
{ question: "What is the output of the following code block?\nchar grade = 'B';\nputchar(grade);", options: ["66", "B", "grade", "Error"], answerIndex: 1 },
{ question: "What will happen if you input a decimal number like 7.89 into the statement: scanf(\"%d\", &intVar); where intVar is an integer?", options: ["The program crashes", "intVar takes 7, and .89 remains in the input buffer", "intVar rounds up and takes 8", "intVar sets itself to 0"], answerIndex: 1 },
{ question: "Which of the following declarations correctly initializes a string of characters in C?", options: ["char str = \"Hello\";", "char str[] = \"Hello\";", "string str = \"Hello\";", "char str[] = 'Hello';"], answerIndex: 1 },
{ question: "What is the output of: printf(\"%%\");", options: ["%%", "An empty space", "A single % symbol", "A compilation warning"], answerIndex: 2 },
{ question: "What value does the variable 'result' hold? \nint result = '3' - '0';", options: ["3", "48", "51", "Garbage value"], answerIndex: 0 },
{ question: "Which statement properly reads a line containing a single space between words into two character variables: scanf(\"%c %c\", &c1, &c2);?", options: ["It skips the space automatically and reads the characters", "It captures the space inside c2 if no explicit separation rules are managed", "It generates a syntax fault", "It terminates program input stream execution"], answerIndex: 0 },
{ question: "What is the error in the following statement: int a, b = 5, int c = 10;", options: ["Variables cannot be initialized in line", "Re-specifying the keyword 'int' within a comma-separated list is a syntax error", "Semicolon is missing at the start", "There is no error"], answerIndex: 1 },
{ question: "If you declare: float x = 3 / 2; What value is stored in x?", options: ["1.5", "1.0", "2.0", "0.0"], answerIndex: 1 },
{ question: "What does the specifier %X output when tracking an integer?", options: ["Floating-point scientific notation", "Hexadecimal format with uppercase letters", "Octal representation value", "Unsigned decimal notation"], answerIndex: 1 },
{ question: "What is the size of the string constant \"A\" in memory due to the implicit null terminator?", options: ["1 byte", "2 bytes", "3 bytes", "0 bytes"], answerIndex: 1 },
{ question: "What is the value of x after this logic sequence? \nint x;\nx = 5;\nx = 12;", options: ["5", "12", "17", "Uninitialized"], answerIndex: 1 },
{ question: "What is the output of: \nprintf(\"%d\", 5 == 5);", options: ["true", "5", "1", "0"], answerIndex: 2 },
{ question: "Which assignment is completely valid in standard C environments?", options: ["int val = 3.14;", "char symbol = \"Z\";", "float point = 'A';", "All of these choices are technically allowed via implicit conversion, though values may alter"], answerIndex: 3 },
{ question: "What happens if a format specifier in printf doesn't have a corresponding argument: printf(\"%d %d\", x); where x=5?", options: ["It prints 5 and then throws a syntax error", "It prints 5 followed by an unpredictable garbage value from the stack", "It fails to compile", "It prints 5 and then 0"], answerIndex: 1 },

// PRE-TEST QUESTIONS: Week 3 (Arithmetic Operators, Precedence, Expressions, Type Casting)
{ question: "Which of the following is the standard modulus operator in C?", options: ["/", "\\", "%", "^"], answerIndex: 2 },
{ question: "What does the modulus operator (%) calculate?", options: ["The quotient of a division", "The remainder of an integer division", "The power of an exponential expression", "The square root value"], answerIndex: 1 },
{ question: "Which mathematical operator has the highest precedence among the following choices?", options: ["+", "-", "*", "="], answerIndex: 2 },
{ question: "In C, how is the evaluation order determined when two operators have the same precedence level?", options: ["Random selection", "Associativity rules", "The compiler choose the fastest instruction", "Always right-to-left standard execution"], answerIndex: 1 },
{ question: "What is 'type casting' in C programming?", options: ["Converting structural variables into comments", "Explicitly or implicitly converting a variable from one data type to another", "Allocating massive arrays of hardware registers", "Debugging compilation links"], answerIndex: 1 },
{ question: "Which type conversion occurs automatically without explicit user code intervention?", options: ["Explicit type casting", "Implicit type conversion (Coercion)", "Down-casting pointer logic", "Manual conversion blocks"], answerIndex: 1 },
{ question: "What happens when an integer is divided by another integer in C (e.g., 5 / 2)?", options: ["It produces a precise float value (2.5)", "The fractional part is truncated, returning an integer (2)", "It rounds up to the closest integer (3)", "It produces a compilation alert standard error"], answerIndex: 1 },
{ question: "Which operator is used for assignment in C?", options: ["==", "=", ":=", "->"], answerIndex: 1 },
{ question: "What is the associativity of the standard arithmetic operators like multiplication (*) and division (/)?", options: ["Right-to-Left", "Left-to-Right", "Non-associative", "Random"], answerIndex: 1 },
{ question: "Which of these expressions represents a valid explicit cast of an integer variable 'sum' to a float type?", options: ["(float)sum", "float(sum)", "cast(sum)", "sum(float)"], answerIndex: 0 },
{ question: "What is the associativity of the assignment operator (=)?", options: ["Left-to-Right", "Right-to-Left", "Bi-directional", "No associativity rule applies"], answerIndex: 1 },
{ question: "Which binary arithmetic operator has the lowest precedence ranking among the options below?", options: ["*", "%", "/", "-"], answerIndex: 3 },
{ question: "Can the modulus operator (%) be applied to operands of type float or double in standard C?", options: ["Yes, anytime", "No, it strictly requires integer operands", "Only if the values are positive constants", "Only when casting to double dynamically"], answerIndex: 1 },
{ question: "What does data truncation mean during type casting?", options: ["The variable changes its literal name", "Losing the fractional or precision part of a value when forcing it into a narrower data type", "The code fails to execute on the CPU", "Memory addresses get corrupted"], answerIndex: 1 },
{ question: "What does an expression consisting of '7 + 3 * 2' evaluate to according to order of operations?", options: ["20", "13", "14", "12"], answerIndex: 1 },
{ question: "Which of these is a compound assignment operator?", options: ["==", "+=", "++", "&&"], answerIndex: 1 },
{ question: "When mixing an 'int' and a 'float' in an arithmetic operation, what is the type of the resulting value?", options: ["int", "char", "float", "long int"], answerIndex: 2 },
{ question: "What math function from <math.h> is used to compute the power of a base raised to an exponent?", options: ["exp()", "pow()", "sqrt()", "pwr()"], answerIndex: 1 },
{ question: "What is the purpose of parentheses '( )' in mathematical programming expressions?", options: ["To define comments safely", "To override standard operator precedence and force specific evaluation order", "To initiate preprocessor blocks", "To declare local constants"], answerIndex: 1 },
{ question: "What value is generated by the expression: 15 % 4?", options: ["3", "1", "0", "2"], answerIndex: 0 },
{ question: "Which conversion can lead to data loss or narrowing precision errors?", options: ["int to float", "char to int", "double to int", "float to double"], answerIndex: 2 },
{ question: "What does the expression 'a = b = c = 5;' do?", options: ["Causes a syntax error", "Assigns the value 5 to variables c, b, and a from right to left", "Checks if a, b, and c are equal to 5", "Assigns 5 only to variable a"], answerIndex: 1 },
{ question: "What is the mathematical outcome of '0 % 5' in standard execution?", options: ["0", "5", "Undefined", "1"], answerIndex: 0 },
{ question: "What is the equivalent expression of: x = x * (y + 2);?", options: ["x *= y + 2;", "x = x * y + 2;", "x *+= y + 2;", "x =*= y + 2;"], answerIndex: 0 },
{ question: "What occurs if you attempt to calculate standard division by a zero constant in an expression (e.g., 10 / 0)?", options: ["Evaluates to 0 safely", "Triggers a compile-time block or an immediate runtime exception/crash", "Evaluates to infinity without error", "Changes the operand to 1"], answerIndex: 1 },

// POST-TEST QUESTIONS: Week 3 (Arithmetic Operators, Precedence, Expressions, Type Casting)
{ question: "What is the exact value of result? \nint result = 5 + 3 * 4 / 2;", options: ["16", "11", "22", "10"], answerIndex: 1 },
{ question: "What is the output of the following block? \nfloat val = 5 / 2;\nprintf(\"%.1f\", val);", options: ["2.5", "2.0", "3.0", "0.0"], answerIndex: 1 },
{ question: "Evaluate the output: \nint ans = 17 % 5 % 2;\nprintf(\"%d\", ans);", options: ["2", "0", "1", "3"], answerIndex: 2 },
{ question: "What is stored in x after execution? \nfloat x = (float)7 / 2;", options: ["3.0", "3.5", "2.0", "4.0"], answerIndex: 1 },
{ question: "What is the output of the following segment?\nint a = 10, b = 3;\nfloat res = a / (float)b;\nprintf(\"%.2f\", res);", options: ["3.00", "3.33", "3.34", "3.03"], answerIndex: 1 },
{ question: "Evaluate the final result: \nint x = 4;\nint y = 3 + (x = 5);\nWhat is the value of y?", options: ["7", "8", "12", "9"], answerIndex: 1 },
{ question: "What does this code print?\nint x = 8;\nx += 4 * 2;\nprintf(\"%d\", x);", options: ["24", "16", "32", "20"], answerIndex: 1 },
{ question: "What is the output of the following valid C statement? \nprintf(\"%d\", -10 % 3);", options: ["-1", "1", "0", "-3"], answerIndex: 0 },
{ question: "What value does 'res' contain? \nint res = (int)5.89 + (int)2.12;", options: ["7", "8", "5", "6"], answerIndex: 0 },
{ question: "Evaluate the expression logic: \nint a = 12, b = 4, c = 2;\nint ans = a / b * c;\nprintf(\"%d\", ans);", options: ["1", "6", "8", "12"], answerIndex: 1 },
{ question: "What value is stored in 'num' after this statement? \nint num = 2.5 * 2;", options: ["5.0", "5", "4", "Garbage value"], answerIndex: 1 },
{ question: "What does this output?\nprintf(\"%d\", 5 / 2 * 2);", options: ["5", "4", "2", "2.5"], answerIndex: 1 },
{ question: "Given: int a = 5; float b = 2.5; What is the data type of the expression (a * b)?", options: ["int", "double", "float", "long"], answerIndex: 2 },
{ question: "What is the value of 'val' after evaluation? \nint val = 10;\nval *= 3 + 2;", options: ["32", "50", "40", "35"], answerIndex: 1 },
{ question: "What is the output of the following C segment?\nint x = 3, y = 4, z = 5;\nint res = x * y + z / 2;\nprintf(\"%d\", res);", options: ["14", "14.5", "12", "8"], answerIndex: 0 },
{ question: "Evaluate the expression value: \nint answer = (20 - 5) * (3 + 1) / 2;", options: ["30", "37", "60", "15"], answerIndex: 0 },
{ question: "What is printed by: \nprintf(\"%.1f\", (double)10 / 4);", options: ["2.0", "2.5", "3.0", "2.2"], answerIndex: 1 },
{ question: "What is the output of the following snippet?\nint a = 5;\nint b = a % 2;\nprintf(\"%d\", b);", options: ["2", "1", "0", "2.5"], answerIndex: 1 },
{ question: "What is stored in 'chk' after evaluation? \nint chk = 1 / 2 * 100;", options: ["50", "0", "100", "0.5"], answerIndex: 1 },
{ question: "What does the following statement output?\nprintf(\"%d\", 2 + 3 * 4 - 5);", options: ["15", "9", "5", "14"], answerIndex: 1 },
{ question: "What happens if a calculation overshoots the maximum storage capacity limits of an integer data type variable?", options: ["The variable defaults back to 0 safely", "Integer overflow occurs, wrapping the value around according to system limits", "The compiler issues a static structural runtime exception stop", "The program automatically scales to a float"], answerIndex: 1 },
{ question: "Evaluate the following operation sequence value: \nint x = 25;\nx = x - 5 * 2;\nprintf(\"%d\", x);", options: ["40", "15", "20", "30"], answerIndex: 1 },
{ question: "What value is produced by this casting block? \ndouble pi = 3.14159;\nint truncated_pi = (int)pi;\nprintf(\"%d\", truncated_pi);", options: ["3", "4", "3.14", "0"], answerIndex: 0 },
{ question: "What is the result of the expression: 12.0 / 4 + 2?", options: ["5", "5.0", "3.0", "2.0"], answerIndex: 1 },
{ question: "What is the value of total after execution?\nint total = 100;\ntotal = total % 30;\nprintf(\"%d\", total);", options: ["10", "3", "30", "1"], answerIndex: 0 }
];

module.exports = {
  w2_pre: questions.slice(0, 25),
  w2_post: questions.slice(25, 50),
  w3_pre: questions.slice(50, 75),
  w3_post: questions.slice(75, 100)
};
