const questions = [
// PRE-TEST QUESTIONS: Week 4 (Relational, Logical, Bitwise, Increment/Decrement Operators)
{ question: "Which of the following is the standard logical AND operator in C?", options: ["&", "&&", "|", "||"], answerIndex: 1 },
{ question: "What value does C use to represent a logical 'true' outcome when evaluating expressions?", options: ["Only 1", "Any non-zero value", "Only positive numbers", "Any value including 0"], answerIndex: 1 },
{ question: "Which operator is used to test if two values are exactly equal to each other?", options: ["=", "==", "===", "!="], answerIndex: 1 },
{ question: "What is the difference between the post-increment operator (x++) and pre-increment operator (++x)?", options: ["x++ increments before evaluating, ++x increments after", "++x increments before evaluating, x++ increments after", "There is no functional difference in any expression", "x++ adds 2, ++x adds 1"], answerIndex: 1 },
{ question: "Which operator performs a bitwise inversion (NOT) turning 0s to 1s and 1s to 0s?", options: ["!", "~", "^", "&"], answerIndex: 1 },
{ question: "What is the result of the logical expression (5 > 3 && 2 < 1)?", options: ["1", "0", "True", "False"], answerIndex: 1 },
{ question: "Which of the following is the bitwise XOR operator in C?", options: ["&&", "||", "^", "~"], answerIndex: 2 },
{ question: "What is the primary characteristic of the logical OR (||) operator?", options: ["It returns true only if both operands are true", "It returns true if at least one operand is true", "It returns true only if both operands are false", "It inverts the truth value of its operand"], answerIndex: 1 },
{ question: "Which relational operator matches the description 'not equal to'?", options: ["<>", "!=", "==", "=! "], answerIndex: 1 },
{ question: "What does the expression 'x >>= 1' do to an integer variable x at the bitwise level?", options: ["Multiplies x by 2", "Divides x by 2 by shifting bits one position to the right", "Sets all bits of x to 1", "Inverts the sign bit of x"], answerIndex: 1 },
{ question: "Which operator is classified as a unary operator?", options: ["+", "&&", "++", "<="], answerIndex: 2 },
{ question: "What is the behavior of 'short-circuit evaluation' in a logical OR (||) expression?", options: ["Both sides are evaluated simultaneously", "If the left-hand side is true, the right-hand side is completely skipped", "If the left-hand side is false, the right-hand side is skipped", "The expression crashes if a zero is encountered"], answerIndex: 1 },
{ question: "Which operator has a higher precedence rank than logical AND (&&)?", options: ["Logical OR (||)", "Assignment (=)", "Relational greater-than (>)", "Comma operator (,)"], answerIndex: 2 },
{ question: "What bitwise operator gives a 1 output bit only when both corresponding input bits are 1?", options: ["|", "&", "^", "~"], answerIndex: 1 },
{ question: "If an integer x holds the value 5, what does the expression (!x) evaluate to?", options: ["-5", "1", "0", "True"], answerIndex: 2 },
{ question: "Which operator is used to shift the bits of a value to the left?", options: [">>", "<<", "<", "<-"], answerIndex: 1 },
{ question: "What is the output bit when applying the bitwise XOR (^) operator to two identical bits (e.g., 1 ^ 1 or 0 ^ 0)?", options: ["1", "0", "Depends on the system architecture", "It toggles dynamically"], answerIndex: 1 },
{ question: "Which of these expressions decrements the variable variable 'counter' by 1?", options: ["counter -= 1;", "counter--;", "--counter;", "All of these choices are valid"], answerIndex: 3 },
{ question: "What is the associativity rule for prefix increment and decrement operators?", options: ["Left-to-Right", "Right-to-Left", "No associativity", "Random"], answerIndex: 1 },
{ question: "Which of the following is NOT a relational operator in C?", options: ["<=", ">=", "==", "~="], answerIndex: 3 },
{ question: "What does the logical NOT (!) operator do?", options: ["Converts any number to 0 directly", "Reverses the logical state of an expression (true to false, false to true)", "Performs a bitwise shift", "Multiplies a value by -1"], answerIndex: 1 },
{ question: "What value does standard C assign to an expression that evaluates to false?", options: ["-1", "0", "Null", "Empty"], answerIndex: 1 },
{ question: "What is the bitwise result of shifting the binary representation of 1 (0001) to the left by two positions (1 << 2)?", options: ["2 (0010)", "4 (0100)", "8 (1000)", "0 (0000)"], answerIndex: 1 },
{ question: "In the expression hierarchy, which operators are processed last?", options: ["Arithmetic operators", "Relational operators", "Logical operators", "Assignment operators"], answerIndex: 3 },
{ question: "Which bitwise operation is commonly used to mask and clear specific bits to 0?", options: ["Bitwise OR (|)", "Bitwise AND (&)", "Bitwise XOR (^)", "Bitwise NOT (~)"], answerIndex: 1 },

// POST-TEST QUESTIONS: Week 4 (Relational, Logical, Bitwise, Increment/Decrement Operators)
{ question: "What is the output of this program segment?\nint x = 5;\nint y = x++;\nprintf(\"%d %d\", x, y);", options: ["5 5", "6 5", "6 6", "5 6"], answerIndex: 1 },
{ question: "Evaluate the final output:\nint a = 10, b = 20;\nint res = (a > 15) && (b = 30);\nprintf(\"%d %d\", res, b);", options: ["0 20", "0 30", "1 30", "1 20"], answerIndex: 0 },
{ question: "What is the value of 'ans' after execution?\nint x = 5, y = 10;\nint ans = (x < y) || (x++ == 5);\nprintf(\"%d\", x);", options: ["5", "6", "7", "0"], answerIndex: 0 },
{ question: "What is the exact output of the following block?\nint a = 3, b = 2;\nprintf(\"%d\", a & b);", options: ["5", "1", "0", "2"], answerIndex: 2 },
{ question: "Evaluate the outcome:\nint x = 2;\nprintf(\"%d\", x << 3);", options: ["16", "8", "6", "12"], answerIndex: 0 },
{ question: "What is printed by this code?\nint x = 5;\nprintf(\"%d\", ++x + 2);", options: ["7", "8", "6", "9"], answerIndex: 1 },
{ question: "What is the value of 'z' after execution?\nint x = 1, y = 0;\nint z = x || y && y;\nprintf(\"%d\", z);", options: ["0", "1", "2", "Syntax Error"], answerIndex: 1 },
{ question: "What does this output reveal?\nint a = 5, b = 5;\nprintf(\"%d\", a != b);", options: ["1", "0", "true", "false"], answerIndex: 1 },
{ question: "Determine the output:\nint m = 4, n;\nn = --m;\nprintf(\"%d %d\", m, n);", options: ["4 3", "3 4", "3 3", "4 4"], answerIndex: 2 },
{ question: "What is the output of the expression: printf(\"%d\", 5 ^ 5);", options: ["10", "0", "25", "1"], answerIndex: 1 },
{ question: "What is printed by the following snippet?\nint val = 0;\nprintf(\"%d\", !val);", options: ["0", "1", "-1", "true"], answerIndex: 1 },
{ question: "What is the structural issue or output of: \nint x = 10;\nint y = ++(x + 5);", options: ["Outputs 16", "Outputs 15", "Compilation error because the increment operator requires an l-value (modifiable variable location)", "Outputs 11"], answerIndex: 2 },
{ question: "What is the result of the bitwise expression: 4 | 1?", options: ["5", "4", "1", "0"], answerIndex: 0 },
{ question: "What is printed by this block?\nint a = 10, b = 5;\nprintf(\"%d\", a > b ? a : b);", options: ["10", "5", "1", "0"], answerIndex: 0 },
{ question: "Evaluate this code trace:\nint x = 10, y = 20;\nint chk = (x == 10) + (y == 20);\nprintf(\"%d\", chk);", options: ["0", "1", "2", "Error"], answerIndex: 2 },
{ question: "What is the result of executing: \nint x = -1;\nprintf(\"%d\", x && 5);", options: ["0", "5", "1", "-1"], answerIndex: 2 },
{ question: "What value does result hold?\nint x = 12; // Binary: 1100\nint result = x >> 2;", options: ["6", "3", "4", "12"], answerIndex: 1 },
{ question: "What output is visible?\nint a = 5, b = 10, c = 15;\nprintf(\"%d\", a < b < c);", options: ["1", "0", "True", "False"], answerIndex: 0 },
{ question: "What occurs here?\nint x = 2;\nint y = x++ + ++x;\nprintf(\"%d\", y);", options: ["6", "5", "4", "Undefined behavior according to standard sequence points, but often evaluates to 6 or 5 depending on compiler"], answerIndex: 3 },
{ question: "What is printed by the following expression?\nprintf(\"%d\", 10 > 5 && 5 > 20);", options: ["1", "0", "true", "false"], answerIndex: 1 },
{ question: "What is the value of 'mask' after processing?\nint mask = ~0;\nprintf(\"%d\", mask == 0);", options: ["1", "0", "Depends on platform bits", "Error"], answerIndex: 1 },
{ question: "Evaluate the code trace:\nint i = 5;\nprintf(\"%d\", i++ + i++);", options: ["10", "11", "12", "The expression exhibits undefined sequence behaviors, parsing differently among compilers"], answerIndex: 3 },
{ question: "What is the output of the statement below?\nprintf(\"%d\", (100 > 50) || (200 < 100));", options: ["1", "0", "100", "50"], answerIndex: 0 },
{ question: "If int x = 7; What is the value of expression (x % 2 == 0)?", options: ["1", "0", "7", "2"], answerIndex: 1 },
{ question: "What is printed by: \nint x = 10;\nprintf(\"%d\", x == 10 || x++);\nprintf(\" %d\", x);", options: ["1 10", "1 11", "0 10", "0 11"], answerIndex: 0 },

// PRE-TEST QUESTIONS: Week 5 (Branching and Decision Making)
{ question: "Which C keyword is used to initiate a basic conditional selection structure?", options: ["while", "switch", "if", "for"], answerIndex: 2 },
{ question: "What type of expression must be placed inside an 'if' statement's condition parentheses?", options: ["An arithmetic formula only", "An expression that evaluates to a logical or numerical value", "A variable declaration statement", "A string literal value"], answerIndex: 1 },
{ question: "What is the purpose of the 'else' clause in an if-else structure?", options: ["To repeat a code block infinitely", "To execute an alternative block of code when the 'if' condition evaluates to false", "To terminate the main function program", "To declare local constant variables"], answerIndex: 1 },
{ question: "When checking multiple alternative mutually exclusive conditions in sequence, which structure is best suited?", options: ["Nested if blocks only", "An else-if ladder multi-way branch", "A series of independent separate if blocks", "An infinite while loop"], answerIndex: 1 },
{ question: "Which statement about the 'switch-case' control structure is true?", options: ["It can evaluate conditions tracking complex float values", "It evaluates an expression and matches it against multiple constant integer or character cases", "It executes all cases simultaneously without order", "It replaces the need for any functions"], answerIndex: 1 },
{ question: "What keyword is typically used inside a switch-case block to prevent execution from falling through into subsequent cases?", options: ["continue", "exit", "break", "return"], answerIndex: 2 },
{ question: "What is the role of the 'default' label inside a switch-case statement?", options: ["It is executed first always before matching", "It executes if none of the explicit case constants match the tested expression", "It forces the application to reboot", "It handles all floating point bounds calculations"], answerIndex: 1 },
{ question: "Is the 'default' label mandatory inside every switch-case statement in C?", options: ["Yes, it is syntactically required", "No, it is entirely optional, though highly recommended for robustness", "Only when handling character cases", "Only if there are more than 5 cases"], answerIndex: 1 },
{ question: "What structural problem can happen if you nest too many levels of 'if' statements inside each other?", options: ["The program size doubles automatically", "Code becomes complex, hard to trace, and less readable ('arrow anti-pattern')", "The preprocessor drops external headers", "The linker rejects the final file structure"], answerIndex: 1 },
{ question: "Which operator is a compact shorthand alternative for a basic if-else decision structure?", options: ["Logical AND (&&)", "The ternary/conditional operator (? :)", "Bitwise XOR (^)", "Compound assignment (+=)"], answerIndex: 1 },
{ question: "What data type constants are strictly forbidden as labels in a standard switch-case construct?", options: ["int constants", "char constants", "float or double constants", "enum constants"], answerIndex: 2 },
{ question: "What happens if an 'if' condition evaluates to a negative integer value like -5?", options: ["It is treated as false because it is less than 0", "It is treated as true because it is a non-zero value", "It causes a compilation crash fault", "It triggers the default case immediately"], answerIndex: 1 },
{ question: "If an 'if' statement has no curly braces '{}' surrounding its body, how many statements are considered part of its execution block?", options: ["Zero statements", "Exactly one subsequent statement", "All lines until the next keyword", "All lines within the active function"], answerIndex: 1 },
{ question: "Which clause is matched with an 'if' statement when resolving the 'dangling else' logical ambiguity in nested constructs?", options: ["The absolute first 'if' statement in the file", "The nearest preceding 'if' statement in the same block that doesn't have an else", "The default case block", "The main function closure brace"], answerIndex: 1 },
{ question: "What type of error is introduced if a programmer writes a semicolon immediately after an if condition: if (x > 5); { x = 0; }", options: ["A fatal compilation error", "A logical error where the block always executes because the if body is empty", "A linker symbol mismatch", "A memory access protection fault"], answerIndex: 1 },
{ question: "Can a switch-case statement have two case labels with the exact same constant value?", options: ["Yes, anytime", "No, duplicate case values are a compilation error", "Only if they contain break statements", "Only if they target char types"], answerIndex: 1 },
{ question: "Which of the following describes 'branching' in computer programming?", options: ["Splitting variables into arrays", "Altering the sequential execution path of a program based on structural conditional tests", "Including multiple external file packages", "Optimizing code execution speeds"], answerIndex: 1 },
{ question: "What are the three expressions separated by inside a standard conditional ternary operator block?", options: ["Semicolons (; ;)", "Commas (, ,)", "A question mark and a colon (? :)", "Arrows (-> =>)"], answerIndex: 2 },
{ question: "What happens to execution in a switch statement if a matching case block does NOT end with a 'break' statement?", options: ["The program immediately terminates", "Execution continues sequentially directly into the next case's statements ('fall-through')", "The compiler raises a terminal error", "The default case runs instead"], answerIndex: 1 },
{ question: "Which keyword can be used alongside 'if' to create a multi-way branch conditional sequence?", options: ["then", "else if", "otherwise", "switch if"], answerIndex: 1 },
{ question: "Which expression format is valid for a case label in a switch statement?", options: ["case 1:", "case x:", "case > 5:", "case 1.5:"], answerIndex: 0 },
{ question: "What is the value of the ternary expression: (10 < 20) ? 100 : 200;", options: ["10", "20", "100", "200"], answerIndex: 2 },
{ question: "What rule governs the execution order of an else-if ladder structure?", options: ["All conditions are evaluated and all matching blocks run", "Conditions are evaluated sequentially from top to bottom; the first true condition block executes, and the rest are skipped", "The compiler chooses randomly", "The shortest block runs first"], answerIndex: 1 },
{ question: "When evaluating an 'if' statement, what happens if the condition is false and no matching 'else' or 'else if' block exists?", options: ["The program crashes", "The control flow simply moves past the if block to the next sequential statement", "The main function restarts", "The compiler generates a warning prompt"], answerIndex: 1 },
{ question: "Which of these is structurally equivalent to an else-if ladder when matching exact integer matching targets?", options: ["A nested for loop block", "A clean switch-case block", "A single basic arithmetic line", "An external preprocessor macro definition"], answerIndex: 1 },

// POST-TEST QUESTIONS: Week 5 (Branching and Decision Making)
{ question: "What is the output of this program segment?\nint x = 10;\nif (x = 5)\n  printf(\"True\");\nelse\n  printf(\"False\");", options: ["True", "False", "No output", "Compilation Error"], answerIndex: 0 },
{ question: "Evaluate the output of the following block:\nint score = 75;\nif (score > 50)\n  printf(\"Pass \");\nif (score > 70)\n  printf(\"Good\");", options: ["Pass", "Good", "Pass Good", "No output is generated"], answerIndex: 2 },
{ question: "What is printed by this code snippet?\nint x = 2;\nswitch(x) {\n  case 1: printf(\"One \");\n  case 2: printf(\"Two \");\n  case 3: printf(\"Three\");\n}", options: ["Two", "Two Three", "One Two Three", "Three"], answerIndex: 1 },
{ question: "Trace the value of y:\nint x = 5;\nint y = (x > 3) ? (x < 10 ? 1 : 2) : 3;\nprintf(\"%d\", y);", options: ["1", "2", "3", "5"], answerIndex: 0 },
{ question: "What is the output of the following program segment?\nint a = 5, b = 10;\nif (a > 0)\n  if (b < 5)\n    printf(\"X\");\n  else\n    printf(\"Y\");", options: ["X", "Y", "XY", "No output"], answerIndex: 1 },
{ question: "What is the output of this code block?\nint num = 0;\nif (num)\n  printf(\"A\");\nelse\n  printf(\"B\");", options: ["A", "B", "AB", "Error"], answerIndex: 1 },
{ question: "Trace the output of this switch structure:\nint ch = 'B';\nswitch(ch) {\n  case 'A': printf(\"Apple\"); break;\n  case 'B': printf(\"Banana\");\n  default: printf(\" Fruit\");\n}", options: ["Banana", "Banana Fruit", "Fruit", "Apple Banana Fruit"], answerIndex: 1 },
{ question: "What happens during compilation of this segment?\nfloat weight = 55.5;\nswitch(weight) {\n  case 55.5: printf(\"Match\"); break;\n}", options: ["Compiles successfully and prints Match", "Generates a compilation error because switch expressions cannot be floats", "Triggers a runtime exception fault", "Executes the default branch code"], answerIndex: 1 },
{ question: "What is the output of the following segment?\nint x = 10, y = 20;\nif (x > 5 || y++ > 25) {\n  printf(\"%d\", y);\n}", options: ["20", "21", "10", "26"], answerIndex: 0 },
{ question: "Evaluate the code trace:\nint val = 3;\nif (val == 3);\n  printf(\"Hello\");", options: ["Hello is printed", "Hello is skipped", "Compilation error occurs at the semicolon", "The program crashes"], answerIndex: 0 },
{ question: "What is printed by the following script?\nint temp = 35;\nif (temp > 40)\n  printf(\"Hot\");\nelse if (temp > 30)\n  printf(\"Warm\");\nelse\n  printf(\"Cold\");", options: ["Hot", "Warm", "Cold", "Warm Cold"], answerIndex: 1 },
{ question: "What is the output of this statement?\nint x = 1, y = 2;\nprintf(\"%s\", (x > y) ? \"Yes\" : \"No\");", options: ["Yes", "No", "%s", "Error"], answerIndex: 1 },
{ question: "Trace the execution output:\nint i = 1;\nswitch(i) {\n  default: printf(\"D \");\n  case 1: printf(\"1 \");\n  case 2: printf(\"2\");\n}", options: ["1 2", "D 1 2", "1", "D"], answerIndex: 0 },
{ question: "What does this code fragment produce?\nint a = 10;\nif (a > 5) {\n  int a = 20;\n  printf(\"%d \", a);\n}\nprintf(\"%d\", a);", options: ["10 10", "20 20", "20 10", "10 20"], answerIndex: 2 },
{ question: "Evaluate the outcome:\nint x = 5;\nif (x > 2)\n  printf(\"A\");\nelse if (x > 4)\n  printf(\"B\");", options: ["A", "B", "AB", "No output"], answerIndex: 0 },
{ question: "What is the output of the following program section?\nint mark = 40;\nif (mark >= 40) \n  printf(\"Passed\");\nelse;\n  printf(\"Failed\");", options: ["Passed", "Failed", "PassedFailed", "Compilation error"], answerIndex: 2 },
{ question: "Trace the execution value:\nint x = 10, y = 5;\nint max = (x > y) ? x : y;\nprintf(\"%d\", max);", options: ["10", "5", "15", "1"], answerIndex: 0 },
{ question: "What is printed by this structure?\nint n = 2;\nswitch(n) {\n  case 1 + 1: printf(\"Yes\"); break;\n  default: printf(\"No\");\n}", options: ["Yes", "No", "Compilation error due to expression in case label", "Runtime crash"], answerIndex: 0 },
{ question: "What output does this construct generate?\nint x = 0;\nif (x = 0)\n  printf(\"Zero\");\nelse\n  printf(\"Non-Zero\");", options: ["Zero", "Non-Zero", "No output", "Compiler warning conversion fault"], answerIndex: 1 },
{ question: "What is the output of this code snippet?\nint val = 5;\nswitch(val) {\n  case 5:\n    printf(\"Five \");\n  case 10:\n    printf(\"Ten\");\n    break;\n}", options: ["Five", "Ten", "Five Ten", "Five Space"], answerIndex: 2 },
{ question: "Determine the output:\nint a = 3, b = 4;\nif (a < b)\n  printf(\"Lesser\");\nelse\n  printf(\"Greater\");\nprintf(\" Done\");", options: ["Lesser", "Greater Done", "Lesser Done", "Done"], answerIndex: 2 },
{ question: "What is the value of 'result' at completion?\nint x = 12;\nint result = (x % 2 == 0) ? 100 : 200;\nprintf(\"%d\", result);", options: ["12", "0", "100", "200"], answerIndex: 2 },
{ question: "What happens if a switch expression matches a case label but that block contains a 'return' statement instead of a 'break'?", options: ["It falls through to the next case label anyway", "It terminates the entire enclosing function immediately and returns control to the caller", "It triggers a compilation parse error", "It branches to the default block directly"], answerIndex: 1 },
{ question: "What output is generated by this sequence?\nint code = 3;\nswitch(code) {\n  case 1: printf(\"Alpha\"); break;\n  case 2: printf(\"Beta\"); break;\n  default: printf(\"Gamma\");\n}", options: ["Alpha", "Beta", "Gamma", "Alpha Beta Gamma"], answerIndex: 2 },
{ question: "Evaluate the output of the following block:\nint x = 1, y = 1;\nif (--x && ++y)\n  printf(\"True %d %d\", x, y);\nelse\n  printf(\"False %d %d\", x, y);", options: ["True 0 2", "False 0 1", "False 0 2", "True 1 1"], answerIndex: 1 }
];

module.exports = {
  w4_pre: questions.slice(0, 25),
  w4_post: questions.slice(25, 50),
  w5_pre: questions.slice(50, 75),
  w5_post: questions.slice(75, 100)
};
